### ISSUE TITLE
The watch script doesn't rebuild

### ISSUE THREAD

**Issue by ehaynes99** [nanojsx/template#2]
It just restarts the server with the same content that's already in `dist`. I realize this isn't trivial, but the script should probably be removed until it reloads.

**Comment by yandeu** [comment]
> It just restarts the server

Using `npm start`? That should run the `clean` script which should clean `dist/` using [rimraf](https://www.npmjs.com/package/rimraf).

**Comment by ehaynes99** [comment]
I was referring to `npm run dev`, but it seems to be working correctly. I must have done something to mess it up. Sorry!
